/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chenhuaming' at '16-7-12 下午7:50' with Gradle 2.14
 *
 * @author chenhuaming, @date 16-7-12 下午7:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
